"use client";
import { useParams } from "next/navigation";
import { useState } from "react";
import { AdminStatusBadge } from "@/components/admin/admin-ui";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Select, Textarea } from "@/components/ui/form-controls";
import { ErrorState, LoadingState } from "@/components/ui/states";
import { useToast } from "@/components/ui/toast";
import { useAsyncResource } from "@/hooks/use-async-resource";
import { formatDateTime } from "@/lib/format";
import { adminService } from "@/services/admin-service";
import type { AdminSupportStatus } from "@/domain/admin";
export default function SupportDetail(){const{id}=useParams<{id:string}>();const resource=useAsyncResource(()=>adminService.getSupport(id),id);const{toast}=useToast();const[body,setBody]=useState("");const[busy,setBusy]=useState(false);if(resource.loading)return <LoadingState label="Đang tải hội thoại..."/>;if(resource.error||!resource.data)return <ErrorState title="Không thể tải hội thoại" description={resource.error??"Không tìm thấy ticket."} onRetry={resource.reload}/>;const thread=resource.data;async function reply(){if(!body.trim())return;setBusy(true);try{await adminService.sendSupportReply(id,body.trim());setBody("");toast({tone:"success",title:"Đã gửi phản hồi"});resource.reload()}catch(error){toast({tone:"error",title:"Không thể gửi phản hồi",description:error instanceof Error?error.message:"Vui lòng thử lại."})}finally{setBusy(false)}}async function change(status:string){try{await adminService.setSupportStatus(id,status);toast({tone:"success",title:"Đã cập nhật trạng thái"});resource.reload()}catch(error){toast({tone:"error",title:"Không thể cập nhật",description:error instanceof Error?error.message:"Vui lòng thử lại."})}}return <div className="admin-page"><PageHeader eyebrow="ADMIN / SUPPORT" title={thread.ticket.subject} description={`${thread.ticket.id} · ${thread.ticket.customerName}`} actions={<AdminStatusBadge status={thread.ticket.status}/>}/><div className="admin-support-layout"><Card className="admin-conversation"><div className="admin-message-list">{thread.messages.map(message=><div key={message.id} className={`admin-message admin-message--${message.senderType.toLowerCase()}`}><div><strong>{message.senderName}</strong><small>{formatDateTime(message.createdAt)}</small></div><p>{message.body}</p></div>)}</div>{thread.ticket.status!=="CLOSED"?<div className="admin-reply-box"><Textarea label="Phản hồi" value={body} onChange={e=>setBody(e.currentTarget.value)} placeholder="Nhập phản hồi cho khách hàng..."/><Button loading={busy} onClick={reply}>Gửi phản hồi</Button></div>:<div className="inline-alert">Ticket đã đóng. Mở lại trạng thái trước khi phản hồi nếu cần.</div>}</Card><aside className="admin-support-aside"><Card className="admin-detail-card"><h2>Trạng thái</h2><Select value={thread.ticket.status} onChange={e=>change(e.currentTarget.value as AdminSupportStatus)} options={['OPEN','WAITING_CUSTOMER','WAITING_SUPPORT','RESOLVED','CLOSED'].map(value=>({value,label:value}))}/><hr/><p><strong>Khách hàng</strong><br/>{thread.ticket.customerName}<br/><span className="muted-text">{thread.ticket.customerEmail}</span></p><p><strong>Danh mục</strong><br/>{thread.ticket.category}</p></Card></aside></div></div>}
