"use client";
import { useState } from "react";
import { AdminBarChart, AdminMoneyMetric } from "@/components/admin/admin-ui";
import { PageHeader } from "@/components/layout/page-header";
import { Card } from "@/components/ui/card";
import { Select } from "@/components/ui/form-controls";
import { ErrorState, LoadingState } from "@/components/ui/states";
import { useAsyncResource } from "@/hooks/use-async-resource";
import { adminService } from "@/services/admin-service";
export default function Analytics(){const[range,setRange]=useState<"7d"|"30d">("30d");const resource=useAsyncResource(()=>adminService.getAnalytics(range),range);return <div className="admin-page"><PageHeader eyebrow="ADMIN / ANALYTICS" title="Phân tích vận hành" description="Các metric mô tả đúng dữ liệu: customer spend, deposit volume và wallet liability; không gọi là accounting revenue." actions={<Select value={range} onChange={e=>setRange(e.currentTarget.value as "7d"|"30d")} options={[{value:"7d",label:"7 ngày"},{value:"30d",label:"30 ngày"}]}/>}/>{resource.loading?<LoadingState label="Đang tổng hợp dữ liệu..."/>:resource.error||!resource.data?<ErrorState title="Không thể tải analytics" description={resource.error??"Dữ liệu không khả dụng."} onRetry={resource.reload}/>:<><div className="admin-metric-grid"><AdminMoneyMetric label="Wallet liability" value={resource.data.walletLiability} note="Tổng balance khách hàng"/><AdminBarChart title="Đơn theo ngày" values={resource.data.daily.map(x=>({label:x.date.slice(5),value:x.orders}))}/></div><div className="admin-chart-grid"><AdminBarChart title="Customer spend" format="currency" values={resource.data.daily.map(x=>({label:x.date.slice(5),value:x.customerSpend}))}/><AdminBarChart title="Deposit volume" format="currency" values={resource.data.daily.map(x=>({label:x.date.slice(5),value:x.deposits}))}/><AdminBarChart title="Refund volume" format="currency" values={resource.data.daily.map(x=>({label:x.date.slice(5),value:x.refunds}))}/><AdminBarChart title="Khách hàng mới" values={resource.data.daily.map(x=>({label:x.date.slice(5),value:x.newCustomers}))}/><AdminBarChart title="Nền tảng" values={resource.data.platformDistribution.map(x=>({label:x.label,value:x.count}))}/><AdminBarChart title="Trạng thái đơn" values={resource.data.orderStatusDistribution.map(x=>({label:x.status,value:x.count}))}/></div><Card className="admin-section-card"><div className="admin-section-head"><h2>Top services</h2></div><div className="admin-ledger-list">{resource.data.topServices.map(s=><div key={s.id}><span><strong>{s.name}</strong><small>{s.id}</small></span><span><strong>{s.orders} đơn</strong><small>{new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(s.customerSpend)}</small></span></div>)}</div></Card></>}</div>}
