"use client";
import { useMemo, useState } from "react";
import { AdminStatusBadge } from "@/components/admin/admin-ui";
import { PageHeader } from "@/components/layout/page-header";
import { Card } from "@/components/ui/card";
import { SearchInput, Select } from "@/components/ui/form-controls";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/states";
import { Pagination, ResponsiveTable, type TableColumn } from "@/components/ui/table";
import { useAsyncResource } from "@/hooks/use-async-resource";
import { formatCurrency, formatDateTime } from "@/lib/format";
import { adminService } from "@/services/admin-service";
import type { AdminTransaction } from "@/domain/admin";
const columns:TableColumn<AdminTransaction>[]=[{key:"date",header:"Thời gian",render:r=>formatDateTime(r.createdAt)},{key:"customer",header:"Khách hàng",render:r=><div className="table-primary"><strong>{r.customerName}</strong><small>{r.customerEmail}</small></div>},{key:"type",header:"Loại",render:r=>r.type},{key:"status",header:"Trạng thái",render:r=><AdminStatusBadge status={r.status}/>},{key:"amount",header:"Số tiền",render:r=><strong>{formatCurrency(r.amount)}</strong>},{key:"balance",header:"Số dư sau",render:r=>formatCurrency(r.balanceAfter)},{key:"reference",header:"Tham chiếu",render:r=><div className="table-primary"><strong>{r.referenceId||"—"}</strong><small>{r.referenceType}</small></div>}];
export default function Transactions(){const[search,setSearch]=useState("");const[type,setType]=useState("all");const[status,setStatus]=useState("all");const[page,setPage]=useState(1);const dep=useMemo(()=>JSON.stringify({search,type,status,page}),[search,type,status,page]);const resource=useAsyncResource(()=>adminService.listTransactions({search,type,status,page,pageSize:20}),dep);return <div className="admin-page"><PageHeader eyebrow="ADMIN / LEDGER" title="Wallet transactions" description="Audit trail tài chính: nạp tiền, mua hàng, hoàn tiền và điều chỉnh quản trị."/><Card className="admin-filter-card"><div className="admin-filter-grid"><SearchInput value={search} onChange={e=>{setSearch(e.currentTarget.value);setPage(1)}} placeholder="Khách hàng, mô tả, reference..."/><Select value={type} onChange={e=>{setType(e.currentTarget.value);setPage(1)}} options={[{value:"all",label:"Tất cả loại"},...['DEPOSIT','PURCHASE','REFUND','ADJUSTMENT'].map(value=>({value,label:value}))]}/><Select value={status} onChange={e=>{setStatus(e.currentTarget.value);setPage(1)}} options={[{value:"all",label:"Tất cả trạng thái"},...['PENDING','COMPLETED','FAILED','REFUNDED'].map(value=>({value,label:value}))]}/></div></Card>{resource.loading?<LoadingState label="Đang tải ledger..."/>:resource.error?<ErrorState title="Không thể tải giao dịch" description={resource.error} onRetry={resource.reload}/>:!resource.data||!resource.data.items.length?<EmptyState title="Không có giao dịch phù hợp" description="Thử bộ lọc khác."/>:<><ResponsiveTable columns={columns} rows={resource.data.items} getRowKey={r=>r.id} caption="Wallet transaction ledger" renderMobileItem={r=><Card className="admin-mobile-card"><div className="admin-mobile-card__head"><strong>{r.type}</strong><AdminStatusBadge status={r.status}/></div><span>{r.customerName}</span><strong>{formatCurrency(r.amount)}</strong><small>{r.referenceId||r.description}</small></Card>}/><Pagination page={resource.data.page} pageCount={resource.data.pageCount} onPageChange={setPage} className="admin-pagination"/></>}</div>}
