"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { AdminStatusBadge } from "@/components/admin/admin-ui";
import { PageHeader } from "@/components/layout/page-header";
import { Card } from "@/components/ui/card";
import { SearchInput, Select } from "@/components/ui/form-controls";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/states";
import { Pagination, ResponsiveTable, type TableColumn } from "@/components/ui/table";
import { useAsyncResource } from "@/hooks/use-async-resource";
import { formatDateTime } from "@/lib/format";
import { adminService } from "@/services/admin-service";
import type { AdminSupportTicket } from "@/domain/admin";
const columns:TableColumn<AdminSupportTicket>[]=[{key:"id",header:"Ticket",render:r=><Link className="text-link" href={`/admin/support/${r.id}`}>{r.id}</Link>},{key:"customer",header:"Khách hàng",render:r=><div className="table-primary"><strong>{r.customerName}</strong><small>{r.customerEmail}</small></div>},{key:"subject",header:"Chủ đề",render:r=><div className="table-primary"><strong>{r.subject}</strong><small>{r.category}</small></div>},{key:"status",header:"Trạng thái",render:r=><AdminStatusBadge status={r.status}/>},{key:"created",header:"Tạo lúc",render:r=>formatDateTime(r.createdAt)},{key:"updated",header:"Cập nhật",render:r=>formatDateTime(r.updatedAt)}];
export default function Support(){const[search,setSearch]=useState("");const[status,setStatus]=useState("all");const[page,setPage]=useState(1);const dep=useMemo(()=>JSON.stringify({search,status,page}),[search,status,page]);const resource=useAsyncResource(()=>adminService.listSupport({search,status,page,pageSize:20}),dep);return <div className="admin-page"><PageHeader eyebrow="ADMIN / SUPPORT" title="Hỗ trợ khách hàng" description="Hội thoại và trạng thái được đọc/ghi trực tiếp từ database."/><Card className="admin-filter-card"><div className="admin-filter-grid"><SearchInput value={search} onChange={e=>{setSearch(e.currentTarget.value);setPage(1)}} placeholder="Ticket ID, khách hàng, chủ đề..."/><Select value={status} onChange={e=>{setStatus(e.currentTarget.value);setPage(1)}} options={[{value:"all",label:"Tất cả trạng thái"},...['OPEN','WAITING_CUSTOMER','WAITING_SUPPORT','RESOLVED','CLOSED'].map(value=>({value,label:value}))]}/></div></Card>{resource.loading?<LoadingState label="Đang tải yêu cầu hỗ trợ..."/>:resource.error?<ErrorState title="Không thể tải hỗ trợ" description={resource.error} onRetry={resource.reload}/>:!resource.data||!resource.data.items.length?<EmptyState title="Không có ticket phù hợp" description="Thử bộ lọc khác."/>:<><ResponsiveTable columns={columns} rows={resource.data.items} getRowKey={r=>r.id} caption="Yêu cầu hỗ trợ" renderMobileItem={r=><Card className="admin-mobile-card"><div className="admin-mobile-card__head"><Link className="text-link" href={`/admin/support/${r.id}`}>{r.id}</Link><AdminStatusBadge status={r.status}/></div><strong>{r.subject}</strong><span>{r.customerName}</span><small>{formatDateTime(r.updatedAt)}</small></Card>}/><Pagination page={resource.data.page} pageCount={resource.data.pageCount} onPageChange={setPage} className="admin-pagination"/></>}</div>}
