"use client";
import { useState } from "react";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/form-controls";
import { ConfirmDialog } from "@/components/ui/overlays";
import { ErrorState, LoadingState } from "@/components/ui/states";
import { useToast } from "@/components/ui/toast";
import { useAsyncResource } from "@/hooks/use-async-resource";
import { formatDateTime } from "@/lib/format";
import { adminService } from "@/services/admin-service";
import type { AdminSettings } from "@/domain/admin";
function SettingsForm({initial,onSaved}:{initial:AdminSettings;onSaved:()=>void}){const{toast}=useToast();const[form,setForm]=useState(initial);const[busy,setBusy]=useState(false);const[maintenanceConfirm,setMaintenanceConfirm]=useState(false);const patch=<K extends keyof AdminSettings>(key:K,value:AdminSettings[K])=>setForm(cur=>({...cur,[key]:value}));async function save(){setBusy(true);try{await adminService.updateSettings({siteName:form.siteName,supportEmail:form.supportEmail,maintenanceMode:form.maintenanceMode,minimumDeposit:form.minimumDeposit,orderCreationEnabled:form.orderCreationEnabled,supportEnabled:form.supportEnabled});toast({tone:"success",title:"Đã lưu cài đặt"});onSaved()}catch(error){toast({tone:"error",title:"Không thể lưu cài đặt",description:error instanceof Error?error.message:"Vui lòng thử lại."})}finally{setBusy(false)}}function toggleMaintenance(){if(!form.maintenanceMode){setMaintenanceConfirm(true);return}patch('maintenanceMode',false)}return <Card className="admin-form-card"><div className="admin-form-stack"><div className="admin-form-grid"><Input label="Tên website" value={form.siteName} onChange={e=>patch('siteName',e.currentTarget.value)}/><Input label="Email hỗ trợ" type="email" value={form.supportEmail} onChange={e=>patch('supportEmail',e.currentTarget.value)}/><Input label="Nạp tối thiểu (VND)" type="number" min={0} value={form.minimumDeposit} onChange={e=>patch('minimumDeposit',Number(e.currentTarget.value))}/></div><div className="admin-setting-switches"><label><input type="checkbox" checked={form.orderCreationEnabled} onChange={e=>patch('orderCreationEnabled',e.currentTarget.checked)}/><span><strong>Cho phép tạo đơn</strong><small>Tắt để chặn đơn Customer mới.</small></span></label><label><input type="checkbox" checked={form.supportEnabled} onChange={e=>patch('supportEnabled',e.currentTarget.checked)}/><span><strong>Cho phép hỗ trợ</strong><small>Tắt để chặn ticket/reply Customer.</small></span></label><label><input type="checkbox" checked={form.maintenanceMode} onChange={toggleMaintenance}/><span><strong>Maintenance mode</strong><small>Customer thấy màn hình bảo trì; Admin vẫn truy cập bình thường.</small></span></label></div><div className="button-row"><Button loading={busy} onClick={save}>Lưu cài đặt</Button><span className="muted-text">Cập nhật gần nhất: {formatDateTime(form.updatedAt)}</span></div></div><ConfirmDialog open={maintenanceConfirm} onOpenChange={setMaintenanceConfirm} destructive title="Bật chế độ bảo trì?" description="Toàn bộ Customer Application sẽ hiển thị màn hình bảo trì. Admin Console và trang đăng nhập vẫn hoạt động." confirmLabel="Bật bảo trì" onConfirm={()=>patch('maintenanceMode',true)}/></Card>}
export default function Settings(){const resource=useAsyncResource(()=>adminService.getSettings());if(resource.loading)return <LoadingState label="Đang tải cài đặt..."/>;if(resource.error||!resource.data)return <ErrorState title="Không thể tải cài đặt" description={resource.error??"Dữ liệu không khả dụng."} onRetry={resource.reload}/>;return <div className="admin-page"><PageHeader eyebrow="ADMIN / SETTINGS" title="Cài đặt hệ thống" description="Chỉ lưu operational settings. Provider/payment secrets không được lưu tại đây."/><SettingsForm key={resource.data.updatedAt} initial={resource.data} onSaved={resource.reload}/></div>}
